AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam app, oppave1

Globals:
  Function:
    Timeout: 300
    MemorySize: 256

Resources:
  ImageGenFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./hello_world
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment: 
        Variables:
          BUCKET_NAME: "pgr301-couch-explorers"
          PREFIX: "45"
      Policies:
            Statement:
              # Permissions to interact with S3 bucket
              - Effect: Allow
                Action:
                  - "s3:PutObject"
                  - "s3:ListBucket"
                Resource:
                  - "arn:aws:s3:::pgr301-couch-explorers/45/*"
              # Permissions to invoke the Bedrock model
              - Effect: Allow
                Action:
                  - "bedrock:InvokeModel"
                Resource: "*"
      Architectures:
        - x86_64
      Events:
        ImageGen:
          Type: Api
          Properties:
            Path: /generate-image
            Method: post

Outputs:
  ImageGenApi:
    Description: "API Gateway endpoint URL for Prod stage for Image Gen function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/generate-image/"