#push image to docker hub and ecr on push to main branh
name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  push_to_dockerhub:
    name: Push Docker image to Dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: login to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # push to DockerHub
      - name: Build and push Docker image
        run: |
          rev=$(git rev-parse --short HEAD)
          docker build -f ./java_sqs_client/Dockerfile . -t java_sqs_client_45
          docker tag java_sqs_client_45 ${{ secrets.DOCKER_USERNAME }}/java_sqs_client_45:$rev
          docker push ${{ secrets.DOCKER_USERNAME }}/java_sqs_client_45:$rev
          docker tag java_sqs_client_45 ${{ secrets.DOCKER_USERNAME }}/java_sqs_client_45:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/java_sqs_client_45:latest