name: Terraform Deploy

on:
  push:
    branches:
      - main        # Når det er en push til main, skal vi kjøre terraform apply
      - "*-feature" # Eksempel på at push til feature-brancher også kan trigge workflowen

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-west-1"  # Bytt ut med ønsket region

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"  # Velg ønsket Terraform-versjon

      - name: Initialize Terraform #etter den første gangeen init har kjørt så må den fjernes
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'  # Kjør terraform apply kun på main
        run: |
          terraform apply -auto-approve tfplan

      - name: Output SQS URL (for testing)
        if: github.ref == 'refs/heads/main'  # Only run on main branch after apply
        run: |
          SQS_URL=$(aws sqs get-queue-url --queue-name image_async_queue --query 'QueueUrl' --output text)
          echo "SQS URL: $SQS_URL"